	ddr3 u0 (
		.clkatari_clk                     (<connected-to-clkatari_clk>),                     //    clkatari.clk
		.ddrext_mem_a                     (<connected-to-ddrext_mem_a>),                     //      ddrext.mem_a
		.ddrext_mem_ba                    (<connected-to-ddrext_mem_ba>),                    //            .mem_ba
		.ddrext_mem_ck                    (<connected-to-ddrext_mem_ck>),                    //            .mem_ck
		.ddrext_mem_ck_n                  (<connected-to-ddrext_mem_ck_n>),                  //            .mem_ck_n
		.ddrext_mem_cke                   (<connected-to-ddrext_mem_cke>),                   //            .mem_cke
		.ddrext_mem_cs_n                  (<connected-to-ddrext_mem_cs_n>),                  //            .mem_cs_n
		.ddrext_mem_dm                    (<connected-to-ddrext_mem_dm>),                    //            .mem_dm
		.ddrext_mem_ras_n                 (<connected-to-ddrext_mem_ras_n>),                 //            .mem_ras_n
		.ddrext_mem_cas_n                 (<connected-to-ddrext_mem_cas_n>),                 //            .mem_cas_n
		.ddrext_mem_we_n                  (<connected-to-ddrext_mem_we_n>),                  //            .mem_we_n
		.ddrext_mem_reset_n               (<connected-to-ddrext_mem_reset_n>),               //            .mem_reset_n
		.ddrext_mem_dq                    (<connected-to-ddrext_mem_dq>),                    //            .mem_dq
		.ddrext_mem_dqs                   (<connected-to-ddrext_mem_dqs>),                   //            .mem_dqs
		.ddrext_mem_dqs_n                 (<connected-to-ddrext_mem_dqs_n>),                 //            .mem_dqs_n
		.ddrext_mem_odt                   (<connected-to-ddrext_mem_odt>),                   //            .mem_odt
		.ddrint_waitrequest               (<connected-to-ddrint_waitrequest>),               //      ddrint.waitrequest
		.ddrint_readdata                  (<connected-to-ddrint_readdata>),                  //            .readdata
		.ddrint_readdatavalid             (<connected-to-ddrint_readdatavalid>),             //            .readdatavalid
		.ddrint_burstcount                (<connected-to-ddrint_burstcount>),                //            .burstcount
		.ddrint_writedata                 (<connected-to-ddrint_writedata>),                 //            .writedata
		.ddrint_address                   (<connected-to-ddrint_address>),                   //            .address
		.ddrint_write                     (<connected-to-ddrint_write>),                     //            .write
		.ddrint_read                      (<connected-to-ddrint_read>),                      //            .read
		.ddrint_byteenable                (<connected-to-ddrint_byteenable>),                //            .byteenable
		.ddrint_debugaccess               (<connected-to-ddrint_debugaccess>),               //            .debugaccess
		.ddroct_rzqin                     (<connected-to-ddroct_rzqin>),                     //      ddroct.rzqin
		.ddrpll_pll_mem_clk               (<connected-to-ddrpll_pll_mem_clk>),               //      ddrpll.pll_mem_clk
		.ddrpll_pll_write_clk             (<connected-to-ddrpll_pll_write_clk>),             //            .pll_write_clk
		.ddrpll_pll_locked                (<connected-to-ddrpll_pll_locked>),                //            .pll_locked
		.ddrpll_pll_write_clk_pre_phy_clk (<connected-to-ddrpll_pll_write_clk_pre_phy_clk>), //            .pll_write_clk_pre_phy_clk
		.ddrpll_pll_addr_cmd_clk          (<connected-to-ddrpll_pll_addr_cmd_clk>),          //            .pll_addr_cmd_clk
		.ddrpll_pll_avl_clk               (<connected-to-ddrpll_pll_avl_clk>),               //            .pll_avl_clk
		.ddrpll_pll_config_clk            (<connected-to-ddrpll_pll_config_clk>),            //            .pll_config_clk
		.ddrpll_pll_mem_phy_clk           (<connected-to-ddrpll_pll_mem_phy_clk>),           //            .pll_mem_phy_clk
		.ddrpll_afi_phy_clk               (<connected-to-ddrpll_afi_phy_clk>),               //            .afi_phy_clk
		.ddrpll_pll_avl_phy_clk           (<connected-to-ddrpll_pll_avl_phy_clk>),           //            .pll_avl_phy_clk
		.ddrrefclk_clk                    (<connected-to-ddrrefclk_clk>),                    //   ddrrefclk.clk
		.ddrrefresh_local_refresh_req     (<connected-to-ddrrefresh_local_refresh_req>),     //  ddrrefresh.local_refresh_req
		.ddrrefresh_local_refresh_chip    (<connected-to-ddrrefresh_local_refresh_chip>),    //            .local_refresh_chip
		.ddrrefresh_local_refresh_ack     (<connected-to-ddrrefresh_local_refresh_ack>),     //            .local_refresh_ack
		.ddrstatus_local_init_done        (<connected-to-ddrstatus_local_init_done>),        //   ddrstatus.local_init_done
		.ddrstatus_local_cal_success      (<connected-to-ddrstatus_local_cal_success>),      //            .local_cal_success
		.ddrstatus_local_cal_fail         (<connected-to-ddrstatus_local_cal_fail>),         //            .local_cal_fail
		.reset_n_reset_n                  (<connected-to-reset_n_reset_n>),                  //     reset_n.reset_n
		.softreset_n_reset_n              (<connected-to-softreset_n_reset_n>),              // softreset_n.reset_n
		.refresh_clk_clk                  (<connected-to-refresh_clk_clk>)                   // refresh_clk.clk
	);

