#!/bin/bash
export TODAY=`date +'%Y%m%d'`
export VERSION=`cat ../VERSION`
echo "D:$TODAY:"
echo "V:$VERSION:"
cat ../firmware_eclairexl_flash/VAMPIRE.bin |sed -e "s/Date:YYYYMMDD Core:XX/Date:$TODAY Core:$VERSION/" > ../firmware_eclairexl_flash/VAMPIRE.bin_dated
../firmware_eclairexl_flash/mif_file_stuff/zpuromgen ../firmware_eclairexl_flash/VAMPIRE.bin_dated  > zpu_rom.mif_insides
cat ../firmware_eclairexl_flash/mif_file_stuff/rom_prologue_40.vhd  zpu_rom.mif_insides ../firmware_eclairexl_flash/mif_file_stuff/rom_epilogue.vhd  > zpu_rom.mif

if [ $1 != "BUILD" ]; then
    echo Updating existing

    #cp zpu_rom.mif build_COMPOSITE/zpu_rom.mif
    quartus_cdb --update_mif vampire.qpf
    quartus_asm vampire.qpf
    
#    pushd build_PAL_RGB/
#    quartus_cpf --convert ../convertv2.cof
#    popd
else
    echo Skipping update
fi

