M48
; DRILL file {KiCad 9.0.7} date 2026-08-08T12:28:41+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-08T12:28:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.540
%
G90
G05
T1
X93.701Y-86.474
X98.781Y-86.474
T2
X104.47Y-89.294
X143.84Y-89.294
M30
